language: cpp    
compiler: gcc   
before_install:  
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test    
  - sudo apt-get update -qq
  - sudo apt-get install freeglut3-dev   
install: sudo apt-get install g++-5 gcc libbox2d2.3.0 libbox2d-dev
script:
  - sh compile.sh
  - g++ -std=c++11 -c physics.cpp -lBox2D -lGL
sudo: required
dist: trusty 